name: handwriting_app
description: A Flutter app that converts typed text into handwritten style based on sample handwriting
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies for the app
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  image: ^3.3.0
  flutter_svg: ^2.0.9
  path_drawing: ^1.0.1
  provider: ^6.1.1
  share_plus: ^7.2.2
  gallery_saver: ^2.3.2
  flutter_colorpicker: ^1.0.3
  
  # Machine Learning dependencies
  tflite_flutter: ^0.10.4
  tflite_flutter_helper: ^0.3.1
  http: ^1.1.0
  
  # Computer Vision and Image Processing
  opencv_dart: ^1.0.4
  google_ml_kit: ^0.16.3
  
  # Additional utilities
  collection: ^1.17.2
  typed_data: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/fonts/
  
